spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.generate-ddl: false        
  h2:
    console.enabled: true

  application:
    name: zinkworks-atm-api

server:
  port: 8080

zinkworks:
  account:
    url: http://localhost:8090/v1/
